// This file will be auto-generated by running: flutterfire configure
// For now, this is a placeholder that includes minimal defaults

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxxx...', // Replace with your Firebase web API key
    appId: '1:xxx:web:xxx',
    messagingSenderId: 'xxx',
    projectId: 'your-project-id',
    authDomain: 'your-project-id.firebaseapp.com',
    databaseURL: 'https://your-project-id.firebaseio.com',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxxx...', // Replace with your Firebase Android API key
    appId: '1:xxx:android:xxx',
    messagingSenderId: 'xxx',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxxx...', // Replace with your Firebase iOS API key
    appId: '1:xxx:ios:xxx',
    messagingSenderId: 'xxx',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxxx...', // Replace with your Firebase macOS API key
    appId: '1:xxx:macos:xxx',
    messagingSenderId: 'xxx',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxxx...', // Replace with your Firebase Windows API key
    appId: '1:xxx:windows:xxx',
    messagingSenderId: 'xxx',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDxxx...', // Replace with your Firebase Linux API key
    appId: '1:xxx:linux:xxx',
    messagingSenderId: 'xxx',
    projectId: 'your-project-id',
  );

  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'DefaultFirebaseOptions.currentPlatform is not supported for this target platform.\n'
      'Please run `flutterfire configure` to generate the firebase_options.dart file.',
    );
  }
}
